Frontend production update
WycliffeAssociates/DOC pull request #6
Opened 2022-01-26 19:27 UTC by linearcombination

This is a big update which incorporates everyone's commits and accomplishes many desired goals of devops and development. Please read commit logs for details as they have been carefully written.

2022-02-16 21:03 UTC, danparisd requested changes

2022-02-16 21:03 UTC, danparisd commented on .env
> +BACKEND_CORS_ORIGINS='["http://localhost:3000", "http://localhost:8001", "https://irguidev.walink.org"]'
```suggestion
BACKEND_CORS_ORIGINS='["http://localhost:3000", "http://localhost:8001"]'
```
we can leave it like this and set the dev/prod CORS origins via environment variable. I just did this as a hack.

@linearcombination can you make this change so I can merge the PR?

2022-02-16 21:12 UTC, linearcombination commented on .env
> +BACKEND_CORS_ORIGINS='["http://localhost:3000", "http://localhost:8001", "https://irguidev.walink.org"]'
This is complete. Thank you.

2022-02-22 20:30 UTC, danparisd approved these changes

2022-02-22 20:30 UTC, merged